// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqIUs_4q6PY_fRe0LZVCGYkT3b2VigrDk',
    appId: '1:341772231821:web:3e067c5bab3645e6a3eec4',
    messagingSenderId: '341772231821',
    projectId: 'botanik-f1b42',
    authDomain: 'botanik-f1b42.firebaseapp.com',
    storageBucket: 'botanik-f1b42.appspot.com',
    measurementId: 'G-KWHXTK7GX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCghCWbKe5S9JVFJilkvK2cO8mfm-bq7mA',
    appId: '1:341772231821:android:d14c32bfb8520167a3eec4',
    messagingSenderId: '341772231821',
    projectId: 'botanik-f1b42',
    storageBucket: 'botanik-f1b42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD77Y7rKlKeJtCFD8oX8iaqAXoOvIRnjF0',
    appId: '1:341772231821:ios:f2d47b79d0cc0214a3eec4',
    messagingSenderId: '341772231821',
    projectId: 'botanik-f1b42',
    storageBucket: 'botanik-f1b42.appspot.com',
    iosClientId: '341772231821-qcps6ae5qnq8gjr41o6poj244olkn79v.apps.googleusercontent.com',
    iosBundleId: 'com.example.botanik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD77Y7rKlKeJtCFD8oX8iaqAXoOvIRnjF0',
    appId: '1:341772231821:ios:f2d47b79d0cc0214a3eec4',
    messagingSenderId: '341772231821',
    projectId: 'botanik-f1b42',
    storageBucket: 'botanik-f1b42.appspot.com',
    iosClientId: '341772231821-qcps6ae5qnq8gjr41o6poj244olkn79v.apps.googleusercontent.com',
    iosBundleId: 'com.example.botanik',
  );
}
