# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  # Flutter Pod

  use_frameworks!

  # Pods for Runner
  # Here you can add any additional pods you need for your project
  # pod 'SomeDependency'

  # Flutter dependencies
end
